# **Assignment 2 - Working with Pandas**

Objective Learn to create and manipulate dataframes for data analysis.

In [6]:
import pandas as pd

The Pandas library is imported using the alias `pd`.

 Pandas is used for data manipulation and analysis with structures such as DataFrames.

**1. Create a DataFrame with the following data:**

In [13]:
data = {
 'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
 'Age': [24, 27, 22, 32, 29],
 'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
 'Salary': [45000, 54000, 50000, 62000, 47000]
 }
data

{'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
 'Age': [24, 27, 22, 32, 29],
 'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
 'Salary': [45000, 54000, 50000, 62000, 47000]}

In [14]:
df = pd.DataFrame(data)
print(df)

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

DataFrame stores data in a tabular format with rows and columns, making it easy to analyze and manipulate data.

a. Print the first five rows of the DataFrame.

In [15]:
df.head(5)

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

b. Get the summary statistics of the 'Age' and 'Salary' columns.

In [16]:
print(df[['Age', 'Salary']].describe())

             Age        Salary
count   5.000000      5.000000
mean   26.800000  51600.000000
std     3.962323   6730.527468
min    22.000000  45000.000000
25%    24.000000  47000.000000
50%    27.000000  50000.000000
75%    29.000000  54000.000000
max    32.000000  62000.000000

selected the specific columns and then using .describe() we got every details such as count, mean, minimum, maximum, and standard deviation.

c. Calculate the average salary of employees in the 'HR' department.

In [25]:
print(df[df['Department']=="HR"]['Salary'].mean())

46000.0

The employees belonging to the HR department are filtered at df[df['Department']=="HR"] , and their average salary is calculated using the `mean()` function.

2. Add a new column, 'Bonus', which is 10% of the salary.

In [27]:
df['Bonus'] = df['Salary'] * 0.10
df

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
1      Bob   27    Finance   54000  5400.0
2  Charlie   22         IT   50000  5000.0
3    Diana   32  Marketing   62000  6200.0
4      Eve   29         HR   47000  4700.0

In this step, a new column named 'Bonus' is added to the DataFrame. The bonus is calculated as 10% of each employee’s salary. using mathemetical operation *df['Salary'] * 0.10*

3. Filter the DataFrame to show employees aged between 25 and 30.

In [30]:
print(df[(df['Age'] >= 25) & (df['Age'] <= 30)])

  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0

The DataFrame is filtered to display employees whose age is between 25 and 30. with *df[(condition1) & (condition2)]*

4. Group the data by 'Department' and calculate the average salary for each
department.

In [31]:
print(df.groupby('Department')['Salary'].mean())

Department
Finance      54000.0
HR           46000.0
IT           50000.0
Marketing    62000.0
Name: Salary, dtype: float64

The data is grouped by 'Department' using the *df.groupby()* and then average salary is count by *['salary'].mean()* where after df.groupby()['salary'] is added which is done to select the salary column

5. Sort the DataFrame by 'Salary' in ascending order and save the result to a new CSV
file.

In [35]:
sorted_df = df.sort_values(by='Salary')
sorted_df
sorted_df.to_csv('sortedby_salary.csv', index=False)

The dataframe is sorted using *df.sort_values(by='Column_name')*

then it is saved to the new csv file via *.to_csv("New_csv_name")*